# Use a imagem oficial do Python 3.10.17
FROM python:3.10.17-slim

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de dependências (requirements.txt primeiro para aproveitar cache)
COPY ../../../requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante do projeto
COPY ./. .

# Comando para rodar sua aplicação (ajuste conforme necessário)
# CMD ["pip", "install", "--no-cache-dir", "-r", "requirements.txt", "&&", "python", "main.py", "--etl"]